<?php

declare(strict_types=1);

/**
 * This file is part of PHPUnit Coverage Check.
 *
 * (c) Eric Sizemore <admin@secondversion.com>
 * (c) Richard Regeer <rich2309@gmail.com>
 *
 * This source file is subject to the MIT license. For the full copyright,
 * license information, and credits/acknowledgements, please view the LICENSE
 * and README files that were distributed with this source code.
 */

namespace Esi\CoverageCheck\Command;

use Esi\CoverageCheck\Application;
use Esi\CoverageCheck\CoverageCheck;
use Esi\CoverageCheck\Style\CoverageCheckStyle;
use Esi\CoverageCheck\Utils;
use Symfony\Component\Console\Attribute\Argument;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Attribute\Option;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Helper\TableCell;
use Symfony\Component\Console\Helper\TableCellStyle;
use Symfony\Component\Console\Helper\TableSeparator;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Throwable;

/**
 * @see \Esi\CoverageCheck\Tests\Command\CoverageCheckCommandTest
 *
 * @psalm-suppress PropertyNotSetInConstructor
 */
#[AsCommand(
    name: Application::COMMAND_NAME,
    description: Application::APPLICATION_DESCRIPTION,
    help: <<<'TXT'
        The <info>%command.name%</info> command calculates coverage score for the provided clover XML report.

        You must pass a coverage threshold that is acceptable. <info>Min = 1, Max = 100</info>:

        <info>php %command.full_name% /path/to/clover.xml 100</info>

        You may also choose to only return the resulting coverage percentage by using the <info>--only-percentage</info> option:

        <info>php %command.full_name% /path/to/clover.xml 100 --only-percentage</info>

        You may also choose to show a breakdown of coverage by file using the <info>--show-files</info> option:

        <info>php %command.full_name% /path/to/clover.xml 100 --show-files</info>

        You may also choose the width of the table output if using --show-files option:

        <info>php %command.full_name% /path/to/clover.xml 100 --show-files --table-width 120</info>
            or
        <info>php %command.full_name% /path/to/clover.xml 100 --show-files --table-width=120</info>
        TXT
)]
final class CoverageCheckCommand
{
    /**
     * Matches CoverageCheck::ERROR_COVERAGE_BELOW_THRESHOLD, except for '[ERROR]' prefix and '%' on first value.
     *
     * @see CoverageCheck::ERROR_COVERAGE_BELOW_THRESHOLD
     *
     * @internal
     *
     * @since 3.0.0
     */
    public const string ERROR_COVERAGE_BELOW_THRESHOLD = 'Total code coverage is %s which is below the accepted %d%%';

    /**
     * Matches CoverageCheck::ERROR_INSUFFICIENT_DATA, except for '[ERROR]' prefix.
     *
     * @see CoverageCheck::ERROR_INSUFFICIENT_DATA
     *
     * @internal
     *
     * @since 3.0.0
     */
    public const string ERROR_INSUFFICIENT_DATA = 'Insufficient data for calculation. Please add more code.';

    /**
     * Matches CoverageCheck::OK_TOTAL_CODE_COVERAGE, except for '[OK]' prefix and '%' on value.
     *
     * @see CoverageCheck::OK_TOTAL_CODE_COVERAGE
     *
     * @internal
     *
     * @since 3.0.0
     */
    public const string OK_TOTAL_CODE_COVERAGE = 'Total code coverage is %s';

    public const string TABLE_HEADER_COVERAGE = 'Coverage';

    public const string TABLE_HEADER_ELEMENTS = 'Elements (Covered/Total)';

    public const string TABLE_HEADER_FILE = 'File';

    /**
     * @internal
     *
     * @since 3.0.0
     */
    private const string INPUT_ARGUMENT_CLOVERFILE = 'The location of the clover xml file that is generated by PHPUnit.';

    /**
     * @internal
     *
     * @since 3.1.0
     */
    private const string INPUT_ARGUMENT_TABLEWIDTH = 'The output table column width when opting for --show-files';

    /**
     * @internal
     *
     * @since 3.0.0
     */
    private const string INPUT_ARGUMENT_THRESHOLD = 'The coverage threshold that is acceptable. Min = 1, Max = 100';

    /**
     * @internal
     *
     * @since 3.0.0
     */
    private const string INPUT_OPTION_ONLY_PERCENTAGE = 'Only return the resulting coverage percentage';

    /**
     * @internal
     *
     * @since 3.0.0
     */
    private const string INPUT_OPTION_SHOW_FILES = 'Show a breakdown of coverage by file';

    private CoverageCheckStyle $coverageCheckStyle;

    public function __construct(private readonly CoverageCheck $coverageCheck) {}

    public function __invoke(
        InputInterface $input,
        OutputInterface $output,
        #[Argument(description: self::INPUT_ARGUMENT_CLOVERFILE)]
        string $cloverfile,
        #[Argument(description: self::INPUT_ARGUMENT_THRESHOLD)]
        int $threshold,
        #[Option(description: self::INPUT_ARGUMENT_TABLEWIDTH, name: 'table-width', shortcut: 'W')]
        int $tablewidth = 70,
        #[Option(description: self::INPUT_OPTION_ONLY_PERCENTAGE, name: 'only-percentage', shortcut: 'O')]
        bool $onlypercentage = false,
        #[Option(description: self::INPUT_OPTION_SHOW_FILES, name: 'show-files', shortcut: 'F')]
        bool $showfiles = false,
    ): int {
        if ($tablewidth < 70) {
            $tablewidth = 70;
        }

        $this->coverageCheckStyle = new CoverageCheckStyle($input, $output, $tablewidth);

        $this->coverageCheck->cloverFile     = $cloverfile;
        $this->coverageCheck->threshold      = $threshold;
        $this->coverageCheck->onlyPercentage = $onlypercentage;

        try {
            $result = $showfiles ? $this->coverageCheck->processByFile() : $this->coverageCheck->process();
        } catch (Throwable $throwable) {
            $this->coverageCheckStyle->error($throwable->getMessage());

            return Command::INVALID;
        }

        // No metrics
        if ($result === false) {
            $this->coverageCheckStyle->error(self::ERROR_INSUFFICIENT_DATA);

            return Command::FAILURE;
        }

        // --show-files
        if (\is_array($result)) {
            return $this->getFileTable($result);
        }

        // Standard output
        return $this->getResultOutput($result);
    }

    /**
     * @param array{
     *     fileMetrics: array<string, array{coveredMetrics: int, totalMetrics: int, percentage: float|int}>,
     *     totalCoverage: float|int
     * } $result
     */
    private function getFileTable(array $result): int
    {
        $tableRows      = [];
        $coveredMetrics = 0;
        $totalMetrics   = 0;

        foreach ($result['fileMetrics'] as $name => $file) {
            $tableRows[] = [
                $name,
                \sprintf('%d/%d', $file['coveredMetrics'], $file['totalMetrics']),
                new TableCell(
                    Utils::formatCoverage($file['percentage']),
                    [
                        'style' => new TableCellStyle(
                            [
                                'cellFormat' => ($file['percentage'] < $this->coverageCheck->threshold) ? '<error>%s</error>' : '<info>%s</info>',
                            ]
                        ),
                    ]
                ),
            ];

            $coveredMetrics += $file['coveredMetrics'];
            $totalMetrics   += $file['totalMetrics'];
        }

        $tableRows[] = new TableSeparator();
        $tableRows[] = [
            'Overall Totals',
            \sprintf('%d/%d', $coveredMetrics, $totalMetrics),
            new TableCell(
                Utils::formatCoverage($result['totalCoverage']),
                [
                    'style' => new TableCellStyle([
                        'cellFormat' => ($result['totalCoverage'] < $this->coverageCheck->threshold) ? '<error>%s</error>' : '<info>%s</info>',
                    ]),
                ]
            ),
        ];

        $this->coverageCheckStyle->table(
            [self::TABLE_HEADER_FILE, self::TABLE_HEADER_ELEMENTS, self::TABLE_HEADER_COVERAGE],
            $tableRows
        );

        unset($tableRows);

        if ($result['totalCoverage'] < $this->coverageCheck->threshold) {
            return Command::FAILURE;
        }

        return Command::SUCCESS;
    }

    private function getResultOutput(float $result): int
    {
        $formattedCoverage = Utils::formatCoverage($result);

        // Only display the percentage?
        if ($this->coverageCheck->onlyPercentage) {
            // … below the accepted threshold
            if ($result < $this->coverageCheck->threshold) {
                $this->coverageCheckStyle->error($formattedCoverage, true);

                return Command::FAILURE;
            }

            // all good, we meet or exceed the threshold
            $this->coverageCheckStyle->success($formattedCoverage, true);

            return Command::SUCCESS;
        }

        // We want the full message…
        if ($result < $this->coverageCheck->threshold) {
            // … below the accepted threshold
            $this->coverageCheckStyle->error(
                \sprintf(self::ERROR_COVERAGE_BELOW_THRESHOLD, $formattedCoverage, $this->coverageCheck->threshold)
            );

            return Command::FAILURE;
        }

        // all good, we meet or exceed the threshold
        $this->coverageCheckStyle->success(\sprintf(self::OK_TOTAL_CODE_COVERAGE, $formattedCoverage));

        return Command::SUCCESS;
    }
}
