<?php

declare(strict_types=1);

/**
 * This file is part of PHPUnit Coverage Check.
 *
 * (c) Eric Sizemore <admin@secondversion.com>
 * (c) Richard Regeer <rich2309@gmail.com>
 *
 * This source file is subject to the MIT license. For the full copyright,
 * license information, and credits/acknowledgements, please view the LICENSE
 * and README files that were distributed with this source code.
 */

namespace Esi\CoverageCheck\Command;

use Esi\CoverageCheck\Application;
use Esi\CoverageCheck\CoverageCheck;
use Esi\CoverageCheck\Data\Threshold;
use Esi\CoverageCheck\Style\CoverageCheckStyle;
use Esi\CoverageCheck\Utils;
use Symfony\Component\Console\Attribute\Argument;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Attribute\Option;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Helper\TableCell;
use Symfony\Component\Console\Helper\TableCellStyle;
use Symfony\Component\Console\Helper\TableSeparator;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Throwable;

/**
 * @see \Esi\CoverageCheck\Tests\Command\CoverageCheckCommandTest
 *
 * @psalm-suppress PropertyNotSetInConstructor
 */
#[AsCommand(
    name: Application::COMMAND_NAME,
    description: Application::APPLICATION_DESCRIPTION,
    help: <<<'TXT'
        The <info>%command.name%</info> command calculates coverage score for the provided clover xml report.

        You must also pass a coverage threshold that is acceptable. <info>Min = 1, Max = 100</info>:

        <info>php %command.full_name% /path/to/clover.xml 100</info>

        You may also choose to only return the resulting coverage percentage by using the <info>--only-percentage</info> option:

        <info>php %command.full_name% /path/to/clover.xml 100 --only-percentage</info>

        You may also choose to show a breakdown of coverage by file by using the <info>--show-files</info> option:

        <info>php %command.full_name% /path/to/clover.xml 100 --show-files</info>

        You may also choose the width of the table output if using --show-files option:

        <info>php %command.full_name% /path/to/clover.xml 100 --show-files --table-width 120</info>
            or
        <info>php %command.full_name% /path/to/clover.xml 100 --show-files --table-width=120</info>
        TXT
)]
final class CoverageCheckCommand extends Command
{
    /**
     * Matches CoverageCheck::ERROR_COVERAGE_BELOW_THRESHOLD, except for '[ERROR]' prefix and '%' on first value.
     *
     * @see CoverageCheck::ERROR_COVERAGE_BELOW_THRESHOLD
     *
     * @internal
     *
     * @since 3.0.0
     */
    public const string ERROR_COVERAGE_BELOW_THRESHOLD = 'Total code coverage is %s which is below the accepted %s';

    /**
     * Matches CoverageCheck::ERROR_INSUFFICIENT_DATA, except for '[ERROR]' prefix.
     *
     * @see CoverageCheck::ERROR_INSUFFICIENT_DATA
     *
     * @internal
     *
     * @since 3.0.0
     */
    public const string ERROR_INSUFFICIENT_DATA = 'Insufficient data for calculation. Please add more code.';

    /**
     * Matches CoverageCheck::OK_TOTAL_CODE_COVERAGE, except for '[OK]' prefix and '%' on value.
     *
     * @see CoverageCheck::OK_TOTAL_CODE_COVERAGE
     *
     * @internal
     *
     * @since 3.0.0
     */
    public const string OK_TOTAL_CODE_COVERAGE = 'Total code coverage is %s';

    /**
     * @internal
     *
     * @since 3.0.0
     */
    private const string INPUT_ARGUMENT_CLOVERFILE = 'The location of the clover xml file that is generated by PHPUnit.';

    /**
     * @internal
     *
     * @since 3.1.0
     */
    private const string INPUT_ARGUMENT_TABLEWIDTH = 'The output table column width when opting for --show-files';

    /**
     * @internal
     *
     * @since 3.0.0
     */
    private const string INPUT_ARGUMENT_THRESHOLD = 'The coverage threshold that is acceptable. Min = 1, Max = 100';

    /**
     * @internal
     *
     * @since 3.0.0
     */
    private const string INPUT_OPTION_ONLY_PERCENTAGE = 'Only return the resulting coverage percentage';

    /**
     * @internal
     *
     * @since 3.0.0
     */
    private const string INPUT_OPTION_SHOW_FILES = 'Show a breakdown of coverage by file';

    private CoverageCheckStyle $coverageCheckStyle;

    public function __construct(private readonly CoverageCheck $coverageCheck)
    {
        parent::__construct();
    }

    public function __invoke(
        InputInterface $input,
        OutputInterface $output,
        #[Argument(description: self::INPUT_ARGUMENT_CLOVERFILE)]
        string $cloverfile,
        #[Argument(description: self::INPUT_ARGUMENT_THRESHOLD)]
        string $threshold,
        #[Option(description: self::INPUT_ARGUMENT_TABLEWIDTH, name: 'table-width', shortcut: 'W')]
        int $tablewidth = 70,
        #[Option(description: self::INPUT_OPTION_ONLY_PERCENTAGE, name: 'only-percentage', shortcut: 'O')]
        bool $onlypercentage = false,
        #[Option(description: self::INPUT_OPTION_SHOW_FILES, name: 'show-files', shortcut: 'F')]
        bool $showfiles = false,
    ): int {
        if ($tablewidth < 70) {
            $tablewidth = 70;
        }

        $this->coverageCheckStyle = new CoverageCheckStyle($input, $output, $tablewidth);

        $this->coverageCheck
            ->setCloverFile($cloverfile)
            ->setThreshold(Threshold::from($threshold))
            ->setOnlyPercentage($onlypercentage);

        try {
            $result = $showfiles ? $this->coverageCheck->processByFile() : $this->coverageCheck->process();
        } catch (Throwable $throwable) {
            $this->coverageCheckStyle->error($throwable->getMessage());

            return Command::INVALID;
        }

        // No metrics
        if ($result === false) {
            $this->coverageCheckStyle->error(self::ERROR_INSUFFICIENT_DATA);

            return Command::FAILURE;
        }

        // --show-files
        if (\is_array($result)) {
            return $this->getFileTable($result);
        }

        // Standard output
        return $this->getResultOutput($result);
    }

    /**
     * @param array{
     *     fileMetrics: array<string, array{coveredMetrics: int, totalMetrics: int, percentage: float|int}>,
     *     totalCoverage: float|int
     * } $result
     */
    private function getFileTable(array $result): int
    {
        $threshold = $this->coverageCheck->getThreshold();
        $tableRows = [];
        // @todo: Convert to ValueObject?
        $totalElements = ['coveredMetrics' => 0, 'totalMetrics' => 0];
        $metrics = $result['fileMetrics'];
        $totalCoverage = $result['totalCoverage'];

        unset($result);

        foreach ($metrics as $name => $file) {
            $tableRows[] = [
                $name,
                \sprintf('%d/%d', $file['coveredMetrics'], $file['totalMetrics']),
                new TableCell(
                    Utils::formatCoverage($file['percentage']),
                    [
                        'style' => new TableCellStyle(
                            [
                                'cellFormat' => ($file['percentage'] < $threshold->value) ? '<error>%s</error>' : '<info>%s</info>',
                            ]
                        ),
                    ]
                ),
            ];

            $totalElements['coveredMetrics'] += $file['coveredMetrics'];
            $totalElements['totalMetrics'] += $file['totalMetrics'];
        }

        unset($metrics);

        $tableRows[] = new TableSeparator();
        $tableRows[] = [
            'Overall Totals',
            \sprintf('%d/%d', $totalElements['coveredMetrics'], $totalElements['totalMetrics']),
            new TableCell(
                Utils::formatCoverage($totalCoverage),
                ['style' => new TableCellStyle(['cellFormat' => ($totalCoverage < $threshold->value) ? '<error>%s</error>' : '<info>%s</info>',])]
            ),
        ];

        $this->coverageCheckStyle->table(
            ['File', 'Elements (Covered/Total)', 'Coverage'],
            $tableRows
        );

        unset($tableRows);

        if ($totalCoverage < $threshold->value) {
            return Command::FAILURE;
        }

        return Command::SUCCESS;
    }

    private function getResultOutput(float $result): int
    {
        $threshold = $this->coverageCheck->getThreshold();
        $onlyPercentage = $this->coverageCheck->getOnlyPercentage();
        $formattedCoverage = Utils::formatCoverage($result);
        $belowThreshold = $result < $threshold->value;

        // Only display the percentage?
        if ($onlyPercentage) {
            // … below the accepted threshold
            if ($belowThreshold) {
                $this->coverageCheckStyle->error($formattedCoverage, true);

                return Command::FAILURE;
            }

            // all good, we meet or exceed the threshold
            $this->coverageCheckStyle->success($formattedCoverage, true);

            return Command::SUCCESS;
        }

        // We want the full message…
        if ($belowThreshold) {
            // … below the accepted threshold
            $this->coverageCheckStyle->error(
                \sprintf(self::ERROR_COVERAGE_BELOW_THRESHOLD, $formattedCoverage, $threshold)
            );

            return Command::FAILURE;
        }

        // all good, we meet or exceed the threshold
        $this->coverageCheckStyle->success(\sprintf(self::OK_TOTAL_CODE_COVERAGE, $formattedCoverage));

        return Command::SUCCESS;
    }
}
