#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * This file is part of PHPUnit Coverage Check.
 *
 * (c) Eric Sizemore <admin@secondversion.com>
 * (c) Richard Regeer <rich2309@gmail.com>
 *
 * This source file is subject to the MIT license. For the full copyright,
 * license information, and credits/acknowledgements, please view the LICENSE
 * and README files that were distributed with this source code.
 */
$composerAutoloaders = [
    __DIR__ . '/vendor/autoload.php', // Try the vendor directory first
    __DIR__ . '/../../autoload.php',   // Then try the parent directory
];

$loader = false;

foreach ($composerAutoloaders as $autoloadFile) {
    if (\file_exists($autoloadFile)) {
        $loader = include $autoloadFile;
        break;
    }
}

if ($loader === false) {
    die('You must set up the project dependencies, run the following commands:' . PHP_EOL .
        'curl -sS https://getcomposer.org/installer | php' . PHP_EOL .
        'php composer.phar install' . PHP_EOL);
}

use Esi\CoverageCheck\Command\CoverageCheckCommand;
use Esi\CoverageCheck\CoverageCheck;
use Symfony\Component\Console\Application;

$console = new Application('PHPUnit Coverage Check', CoverageCheck::VERSION);
$console->add(new CoverageCheckCommand(new CoverageCheck()));
$console->run();
