<?php

declare(strict_types=1);

/**
 * This file is part of PHPUnit Coverage Check.
 *
 * (c) Eric Sizemore <admin@secondversion.com>
 * (c) Richard Regeer <rich2309@gmail.com>
 *
 * This source file is subject to the MIT license. For the full copyright,
 * license information, and credits/acknowledgements, please view the LICENSE
 * and README files that were distributed with this source code.
 */

namespace Esi\CoverageCheck;

use Exception;
use RuntimeException;
use SimpleXMLElement;

use function file_exists;
use function libxml_clear_errors;
use function libxml_get_errors;
use function libxml_use_internal_errors;
use function property_exists;
use function trim;

use const LIBXML_ERR_ERROR;
use const LIBXML_ERR_FATAL;
use const LIBXML_ERR_WARNING;
use const PHP_EOL;

final class Utils
{
    /**
     * Returns the given number formatted and rounded for percentage.
     */
    public static function formatCoverage(float $number): string
    {
        return \sprintf('%0.2F%%', $number);
    }

    /**
     * Attempts to determine if we are actually using a PHPUnit generated clover file.
     *
     * As of 2024/03/28, the Clover XML report generated by PHPUnit (using phpunit-code-coverage) does
     * not validate against the official Atlassian/OpenClover clover XSD.
     *
     * @see https://bitbucket.org/atlassian/clover/raw/master/etc/schema/clover.xsd
     * @see https://github.com/sebastianbergmann/php-code-coverage/issues/578
     *
     * So this is a workaround of sorts.
     */
    public static function isPossiblyClover(SimpleXMLElement $xml): bool
    {
        if ($xml->getName() !== 'coverage') {
            return false;
        }

        $hasChildren = $xml->children();

        if (
            !property_exists($hasChildren, 'project')
            || !property_exists($hasChildren->project, 'metrics')
            || (array) $hasChildren->project->metrics === []
        ) {
            return false;
        }

        unset($hasChildren);

        return true;
    }

    /**
     * Handles parsing the XML data returned by CoverageCheck::loadMetrics().
     *
     * Attempts to gather any potential errors returned by SimpleXml/LibXml and wrap them
     * in a RuntimeException.
     *
     * @see https://www.php.net/SimpleXMLElement
     * @see https://www.php.net/libxml_use_internal_errors
     * @see https://www.php.net/libxml_get_errors
     *
     * @throws RuntimeException For any xml parser related errors.
     */
    public static function parseXml(string $xmlData): SimpleXMLElement
    {
        static $errorLevels = [
            LIBXML_ERR_WARNING => 'Warning',
            LIBXML_ERR_ERROR   => 'Error',
            LIBXML_ERR_FATAL   => 'Fatal Error',
        ];

        libxml_use_internal_errors(true);

        try {
            $xml = new SimpleXMLElement($xmlData);
        } catch (Exception) {
            $errorMessage = PHP_EOL;

            foreach (libxml_get_errors() as $error) {
                $errorMessage .= \sprintf(
                    '%s %d: %s. Line %d Column %d',
                    $errorLevels[$error->level],
                    $error->code,
                    trim($error->message),
                    $error->line,
                    $error->column
                ) . PHP_EOL;
            }

            throw new RuntimeException(\sprintf('Unable to load Clover XML data. LibXml returned: %s', $errorMessage));
        } finally {
            libxml_clear_errors();
            libxml_use_internal_errors(false);
        }

        return $xml;
    }

    /**
     * A simple file_exists check on the Clover file.
     */
    public static function validateCloverFile(string $cloverFile): bool
    {
        return ($cloverFile !== '' && file_exists($cloverFile));
    }

    /**
     * A simple check to determine if threshold is within accepted range (Min. 1, Max. 100).
     */
    public static function validateThreshold(int $threshold): bool
    {
        return ($threshold > 0 && $threshold <= 100);
    }
}
