name: PHPStan

on:
  workflow_dispatch:
  push:
    branches:
      - "2.x-dev"
  pull_request:
    branches:
      - "2.x-dev"

# Is it overkill to run PHPStan using different PHP versions? Probably :)
jobs:
  phpstan:
    name: "PHPStan Static Analysis  ${{ matrix.php-version }}, ${{ matrix.operating-system }}"
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
        operating-system:
          - "ubuntu-latest"
          - "windows-latest"
    steps:
      - uses: actions/checkout@v4

      - name: "Install PHP ${{ matrix.php-version }}"
        uses: shivammathur/setup-php@master
        with:
           php-version: "${{ matrix.php-version }}"
           extensions: mbstring
           tools: composer:v2

      - name: "Validate composer.json and composer.lock"
        run: composer validate --strict

      - name: "Cache Composer packages"
        id: composer-cache
        shell: bash
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: "Install dependencies"
        run: composer install --prefer-dist --no-progress

      - name: "Run PHPStan"
        run: composer run-script phpstan
